# DIMENSIONES EN NUMPY

In [2]:
import numpy as np

## SCALAR

In [3]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

## VECTOR

In [4]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

## MATRIZ 2 DIMENSIONES

In [5]:
matriz = np.array([
    [1,2,3],
    [4,5,6]
])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

## TENSOR - N DIMENSIONES

In [6]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3