# GENERACIÓN DE DATOS ALEATORIOS

In [1]:
import numpy as np

# ARANGE

In [2]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# ZEROS

In [3]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ONES

In [4]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# EYE

In [5]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# LINSPACE

In [6]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

# RANDOM

In [8]:
np.random.rand()

0.6293217830694496

In [9]:
np.random.rand(4)

array([0.93039197, 0.76480737, 0.78561769, 0.59160441])

In [10]:
np.random.rand(4,4)

array([[0.95086418, 0.69234096, 0.46987058, 0.18065212],
       [0.54476536, 0.91861556, 0.15411164, 0.85913258],
       [0.12063174, 0.66135019, 0.98736867, 0.65036651],
       [0.86978657, 0.66058781, 0.21744618, 0.03187417]])

In [11]:
np.random.randint(1,100,(10,10))

array([[36, 45,  5, 44, 32, 95, 55, 36, 56, 40],
       [68, 57,  3, 42, 34, 48, 57, 21, 16, 26],
       [44,  3, 37, 79, 52, 76, 89,  5,  8, 96],
       [96,  5, 11, 56, 77, 51, 82, 29, 58, 33],
       [35, 98, 27, 99, 65, 97, 36, 48, 30, 72],
       [60, 73, 90, 39, 50, 88, 20,  9, 17,  7],
       [20, 43, 95, 23, 52, 88, 90, 72, 56, 48],
       [18, 61, 36, 87, 15, 90, 23,  1, 70, 32],
       [50, 68,  8, 62, 37, 53, 71, 68, 66, 72],
       [98, 77, 96, 62,  3, 98,  3, 55, 42, 56]])