# COMANDOS LINUX

In [1]:
!ls

sample_data


In [2]:
!pwd

/content


In [ ]:
!pip freeze


In [4]:
!pip install numpy

#IMPORTAR LIBRERIA

In [5]:
import numpy as np

# CONVIRTIENDO LISTAS EN ARRAYS DE NUMPY

In [6]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
type(lista)

list

In [8]:
arr = np.array(lista)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(arr)

numpy.ndarray

# SLICING

In [10]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [11]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

#TIPO DE DATOS EN NUMPY

In [12]:
arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [14]:
arr_float = np.array([1,2,3,4],dtype='float64')
arr_float.dtype
arr_float

array([1., 2., 3., 4.])

# CAST DE TIPO DE DATOS

In [15]:
arr = np.array([0,1,2,3,4])
arr_bool = arr.astype(np.bool_)
arr_bool.dtype

dtype('bool')

In [16]:
arr_bool

array([False,  True,  True,  True,  True])

In [19]:
arr_string = np.array([0,1,2,3,4])
arr_string = arr.astype(np.string_)
arr_string

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')