# FUNCIONES MAS COMUNES EN NUMPY

In [1]:
import numpy as np

## SHAPE Y RESHAPE

In [2]:
arr = np.random.randint(1,10,(3,2))
arr

array([[2, 6],
       [5, 4],
       [2, 2]])

In [3]:
arr.shape

(3, 2)

In [4]:
arr.ndim

2

In [5]:
arr.reshape(1,6)

array([[2, 6, 5, 4, 2, 2]])

In [6]:
arr.ndim

2

# MAX Y ARGMAX

In [8]:
arr = np.random.randint(1,20,10)
arr

array([ 5, 11,  9, 17, 11,  2,  1, 18,  9,  3])

In [9]:
matriz = arr.reshape(2,5)
matriz

array([[ 5, 11,  9, 17, 11],
       [ 2,  1, 18,  9,  3]])

In [10]:
arr.max()

18

In [11]:
matriz.max()

18

In [12]:
matriz.max(1)

array([17, 18])

In [13]:
arr.argmax()

7

## MIN Y ARGMIN

In [14]:
arr.min()

1

In [15]:
arr.argmin()

6

In [16]:
matriz.min(0)

array([2, 1, 9, 9, 3])

## SORT

In [17]:
arr

array([ 5, 11,  9, 17, 11,  2,  1, 18,  9,  3])

In [19]:
arr.sort()
arr

array([ 1,  2,  3,  5,  9,  9, 11, 11, 17, 18])

## MEDIAM

In [20]:
np.median(arr)

9.0

## DESVIACIÓN STANDARD STD

In [21]:
np.std(arr)

5.624944444170093

## VARIZNA VAR

In [22]:
np.var(arr)

31.639999999999997