In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

# FILTROS POR CONDICIONES

In [3]:
indices_condiciones = arr > 5
indices_condiciones

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [4]:
arr[indices_condiciones]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [5]:
arr[arr < 5]

array([1, 2, 3, 4], dtype=int8)

In [6]:
arr[(arr > 5) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [8]:
arr[arr > 5] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [9]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [11]:
arr_2 = arr[arr==99]
arr_2

array([99, 99, 99, 99, 99], dtype=int8)

In [12]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [15]:
arr_2[arr_2 == 5] = 100

In [16]:
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [17]:
arr_2

array([99, 99, 99, 99, 99], dtype=int8)

# COPY

In [18]:
arr = np.linspace(1,10,10,dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [19]:
arr_copy = arr.copy()

In [20]:
arr_copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [21]:
arr_copy[:] = 100

In [22]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100], dtype=int8)

In [23]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)